version: "3.7"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    volumes:
      - ./client/src:/app/src
    ports:
      - 8080:8080

  nest:
    build:
      context: .
      dockerfile: Dockerfile-nest
    container_name: nest
    depends_on:
      - db
    volumes:
      - ./server/src:/app/src
    ports:
      - 3000:3000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nest-nginx
    depends_on:
      - nest
      - frontend
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
      - ANGULAR_HOST=frontend
      - ANGULAR_PORT=8080
    ports:
      - 80:80

  db:
    image: mariadb:10
    container_name: nest-db
    environment:
      MYSQL_DATABASE: conc-orders
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql

  phpmyadmin:
    container_name: conc-orders-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  mariadbdata:
