version: "2"
services:
  nest:
    build: .
    container_name: nest
    depends_on:
      - db
    volumes:
      - ./server:/app/server
      - .env:/app/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nest-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80

  db:
    image: mariadb:10
    container_name: nest-db
    environment:
      MYSQL_DATABASE: conc-orders
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql

  phpmyadmin:
    container_name: conc-orders-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
volumes:
  mariadbdata:
